# Generated by Django 5.2.5 on 2025-08-18 11:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('niveau', models.CharField(choices=[('ADMIN', 'ADMIN'), ('USER-SIMPLE', 'UTILISATEUR SIMPLE')], default='USER-SIMPLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('TO DO', 'À FAIRE'), ('IN PROGRESS', 'EN COURS'), ('DONE', 'TERMINÉE')], default='TO DO', max_length=20)),
                ('priority', models.CharField(choices=[('HIGH', 'H'), ('MEDIUM', 'M'), ('LOW', 'L')], default='MEDIUM', max_length=10)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to='tasks_app.personne')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_created', to='tasks_app.personne')),
            ],
        ),
    ]
