# Generated by Django 5.2.5 on 2025-08-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'Haute'), ('MEDIUM', 'Moyenne'), ('LOW', 'Basse')], default='MEDIUM', max_length=10),
        ),
    ]
